version: "3.9"
services:
  express:
    image: omneex/dandle-backend:main
    ports:
      - "8000:3000"
    links:
      - "redis"
    volumes:
        - type: bind
          source: ./.env
          target: /usr/.env
          read_only: true
    environment:
        - REDIS_HOST=redis
  redis:
    image: redis:6-alpine
    ports:
        - "6379:6379"

