# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, sprint-dev ]
  pull_request:
    branches: [ main, sprint-dev ]
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the branch
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '16.x'
        
    - name: Create env File
      run: |
        touch .env
        echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
    - name: Install Dependencies
      run: npm ci
    - name: Build the Project
      run: npm run build --if-present
    - name: Run the Tests
      run: npm test
